Add download_model
marcom/Llama.jl pull request #9
Opened 2024-01-10 22:22 UTC by svilupp

This PR adds a small utility to make it super easy to download hugging face models locally.

```julia
# Download the Rocket model (~1GB)
url = "https://huggingface.co/ikawrakow/various-2bit-sota-gguf/resolve/main/rocket-3b-2.76bpw.gguf"
model = download_model(url) 
# Output: "models/rocket-3b-2.76bpw.gguf"
```

It's quite restrictive (URL checks) to avoid common pitfalls for first-time users.

As part of the PR, I was checking tests, so I've added Aqua and its badge. 
Happy to remove it but it's a good practice to have it?

2024-01-10 23:00 UTC, marcom requested changes

2024-01-10 23:00 UTC, marcom commented on src/utils.jl
> +    @assert startswith(url, "https://huggingface.co/") || startswith(url, "http://huggingface.co/") "The provided URL is not a HuggingFace Hub model. See https://huggingface.co/"
`@assert` can be disabled due to optimization, an if statement with a throw is more appropriate I think. Why shouldn't other URLs be allowed?

2024-01-10 23:00 UTC, marcom commented on src/utils.jl
> +    model_fn = joinpath(dir, splitpath(url)[end]) # target file name
`model_path` is clearer (as it is not just a filename, which I think the 'fn' is supposed to imply)

2024-01-10 23:03 UTC, marcom commented on src/utils.jl
> +    return model_fn # return the path to the downloaded file
These comments at the end are not needed anymore after changing `model_fn` to `model_path`

2024-01-11 07:29 UTC, svilupp commented on src/utils.jl
> +    @assert startswith(url, "https://huggingface.co/") || startswith(url, "http://huggingface.co/") "The provided URL is not a HuggingFace Hub model. See https://huggingface.co/"
No particular reason, besides forcing the happy path (and avoiding silly mistakes).

 warning with @warn should be sufficient!

Noted on the @assert preference, although I think it’s an extremely rare situation which would be fine for our use case.

2024-01-11 09:07 UTC, svilupp commented
Added also a mention in the README as discussed in the issue about the next steps.

We should be good to go, but I'll wait for your final nod.

2024-01-11 10:06 UTC, marcom commented on src/utils.jl
> +    @assert startswith(url, "https://huggingface.co/") || startswith(url, "http://huggingface.co/") "The provided URL is not a HuggingFace Hub model. See https://huggingface.co/"
Note: the way you wrote `@warn` and `@Assert` (without surrounding backticks) will notify the github users with these usernames of this PR. They probably love julia.

The julia `@assert` docstring has the reasoning, it's the same as in python or C - an assert is a conditional that you don't mind if it were taken out of the code, i.e. it's only for debugging and never for program logic. You are correct that it doesn't matter in this case.

2024-01-11 10:11 UTC, marcom approved these changes
LGTM

2024-01-11 10:13 UTC, svilupp commented on src/utils.jl
> +    @assert startswith(url, "https://huggingface.co/") || startswith(url, "http://huggingface.co/") "The provided URL is not a HuggingFace Hub model. See https://huggingface.co/"
🤦

2024-01-11 10:13 UTC, merged